[project]
authors = [{ name = "quantity-dev contributors" }]
dependencies = ["optype>=0.9.0,<0.10"]
name = "metrology-apis"
requires-python = ">= 3.13"
version = "0.0.1.dev0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
metrology-apis = { path = "." }
optype = ">=0.9.0,<0.10"

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[tool.pixi.package.host-dependencies]
hatchling = "==1.27.0"
